name: Run Scrapy Crawl

on:
  schedule:
    - cron: "0 0 * * 1,4" # Runs every day at midnight UTC

env:
  SCRIPT_EMAIL: ${{ secrets.SCRIPT_EMAIL }}
  SCRIPT_PASS: ${{ secrets.SCRIPT_PASS }}
  

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check Mail Recipients
      run: python config.py
    
    - name: Run Broken Links
      run: scrapy crawl find_broken_links
  
    - name: Run Broken Image
      run: scrapy crawl find_broken_img_and_missing_alt